CREATE DATABASE MercadoDoSeuZeDB

USE MercadoDoSeuZeDB

CREATE TABLE PRODUTO(
    ID_PRODUTO INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(250) NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    PRECO_UNITARIO DECIMAL(11,2) NOT NULL,
    UNIDADE VARCHAR(50) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO)
);

select * from Produto

CREATE TABLE CLIENTE
(
    ID_CLIENTE INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    ENDERECO VARCHAR(250) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
);